[tool.poetry]
name = "validation"
version = "0.0.1"
description = ""
authors = ["Nacho <nacho@sixsq.com>"]
packages = [{include = "validation_framework"}]
readme = "README.md"

[tool.poetry.scripts]
validation = "validation_framework.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"
nuvla-api = "^3.0.8"
fabric = "^2.7.1"
toml = "^0.10.2"
invoke = "^1.7.3"
xmltodict = "^0.13.0"
unittest-xml-reporting = "^3.2.0"
requests = "^2.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
