[tool.poetry]
name = "validation"
version = "0.0.1a1"
description = ""
authors = ["Nacho <nacho@sixsq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"
nuvla-api = "^3.0.8"
pytest = "^7.2.0"
fabric = "^2.7.1"
fastapi = "^0.85.1"
uvicorn = "^0.19.0"
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
