alias = "one_2560"

# Orchestration engine
coe = "docker"

# Network data
address = "192.168.40.206"
port = 2222
hostname = ""

# Naming data
user = "root"

# Security data
pub_key_path = "~/.ssh/id_rsa.pub"
private_key_path = "~/.ssh/id_rsa"
