alias = "ubuntu_VM"

# Network data
address = "159.100.243.225"
port = 22
hostname = ""

# Naming data
user = "ubuntu"

# Security data
pub_key_path = "~/.ssh/id_rsa.pub"
private_key_path = "~/.ssh/id_rsa"

