alias = "rpi4"

# Orchestration engine
coe = "docker"

# Network data
address = "192.168.40.177"
port = 22
hostname = ""

# Naming data
user = "pi"

# Security data
pub_key_path = "~/.ssh/id_rsa.pub"
private_key_path = "~/.ssh/id_rsa"
