alias = "rpi4"

# Orchestration engine
coe = "kubernetes"

# Network data
address = "192.168.40.225"
port = 22
hostname = ""

# Naming data
user = "sixsq"

# Security data
pub_key_path = "~/.ssh/id_rsa.pub"
private_key_path = "~/.ssh/id_rsa"
