alias = "rpi4"

# Orchestration engine
coe = "kubernetes"

# Network data
address = "192.168.40.177"
port = 22
hostname = ""

# Naming data
user = "amitbhanja"

# Security data
pub_key_path = "~/.ssh/id_ed25519.pub"
private_key_path = "~/.ssh/id_ed25519"
