alias = "ubuntu_VM"

# Orchestration engine
coe = "kubernetes"

# Network data
address = "194.182.163.87"
port = 22
hostname = ""

# Naming data
user = "ubuntu"

# Security data
pub_key_path = "~/.ssh/id_rsa.pub"
private_key_path = "~/.ssh/id_rsa"

