alias = "ubuntu_VM"

# Orchestration engine
coe = "docker"

# Network data
address = "185.19.30.169"
port = 22
hostname = ""

# Naming data
user = "root"

# Security data
pub_key_path = "~/.ssh/id_rsa.pub"
private_key_path = "~/.ssh/id_rsa"

