alias = "ubuntu_VM"

# Orchestration engine
coe = "kubernetes"

# Network data
address = "85.217.161.47"
port = 22
hostname = ""

# Naming data
user = "root"

# Security data
pub_key_path = "~/.ssh/id_rsa.pub"
private_key_path = "~/.ssh/id_rsa"

