name: "Build and push the runner image"

on:
    push:
      branches:
        - main
      files:
        - "docker_runner/**"
        - ".github/workflows/build-runner.yml"
    pull_request:

jobs:
  build-runner:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64/v8 ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: ./docker_runner
          file: ./docker_runner/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: >
            nuvladev/nuvlaedge-validation:runner
          cache-from: type=gha
          cache-to: type=gha,mode=max
