name: "Build and push gh-runner image"

on:
    push:
      branches:
        - main
      paths:
        - "docker_runner/**"

jobs:
  build-runner:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker_runner
          file: ./docker_runner/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: >
            nuvladev/nuvlaedge-validation:runner
          cache-from: type=gha
          cache-to: type=gha,mode=max
