name: Validator updater

on:
  push:
    branches:
      - main
    pull_request:
  workflow_dispatch:

env:
  NUVLA_API_KEY: ${{secrets.VALIDATION_API_KEY}}
  NUVLA_API_SECRET: ${{secrets.VALIDATION_API_SECRET}}

jobs:
  update-validator:
    runs-on: validation-runner
    strategy:
      matrix:
        board-config: ["1_rpi4.toml", "2_ubuntu_vm.toml"]

    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting for sonar
          fetch-depth: 0

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Validation on board ${{ matrix.board-config }}
        working-directory: ./validation_framework
        run: python main.py --target ${{ matrix.board-config }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "temp_results/xml/*.xml"
