name: "BUILD"

on:
  push:
    branches:
      - tests
  workflow_dispatch:

jobs:
  build-validator:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.2.2"

      - name: Build package
        run: poetry build --format=wheel

      - name: Create standard latest release
        run: |
          cp ./dist/validation* ./release-history/
          mv ./dist/validation* ./validation-latest-py3-none-any.whl

      - name: Commit changes
        run: |
          git config --local user.email "nuvlaedge-bot@sixsq.com"
          git config --local user.name "nuvlaedge-bot"
          git add -A
          git commit -m "Validation Framework CI action"

      - name: Push release back
        uses: ad-m/github-push-action@master
        env:
          github_token: ${{ secrets.VALIDATION_GITHUB_TOKEN }}
          branch: 'main'
