name: UPDATE

on:
  push:
    branches:
      - main
    pull_request:
    workflow_dispatch:

jobs:
  update-validator:
    runs-on: validation-runner
    strategy:
      matrix:
        board-config: ["1_rpi4.toml"]

    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting for sonar
          fetch-depth: 0

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Validation on board ${{ matrix.board-config }}
        working-directory: ./validation_framework
        run: python main.py
