name: UPDATE

on:
  push:
    branches:
      - main
    pull_request:
    workflow_dispatch:

jobs:
  update-validator:
    runs-on: validation-runner
    steps:
      - name: Pull repo
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting for sonar
          fetch-depth: 0

        - name: Setup Python environment
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: pip install -r requirements.txt
