
# Releases a new version of the Validation framework
# A new tag has to be manually trigger. After that, this workflow tests and validates the new release
# creating the release

name: "Validation Release"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "**"

jobs:
  build-nuvlaedge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SetUp python interpreter
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Load cached poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: dotlocal-${{ runner.os }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Actual library build
        run: |
          poetry build --no-interaction --format=wheel
          cp ./dist/validation* ./dist/validation-latest-py3-none-any.whl

      - name: Release package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Releasing Validation version ${{ github.ref_name }}"
          gh release create ${{ github.ref }} --generate-notes ./dist/* ./conf/targets/*.toml