name: "Update results table"

on:
  repository_dispatch:
    types: [my-event]

jobs:
  update-results:
    runs-on: ubuntu-latest

    steps:
      - name: Pull validation repository
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting for sonar
          fetch-depth: 0

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'

      - name: Refactor current table
        working-directory: ./validation_framework/results_parser
        run: |
          echo "Test dispatch payload \n Actions: ${{ github.event.action }} \n Device: ${{ github.event.client_payload.device }}"
