name: "Update results table"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  update-results:
    runs-on: ${{ github.event.client_payload.dev }}

    steps:
      - name: Pull validation repository
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting for sonar
          fetch-depth: 0

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Refactor current table
        working-directory: ./validation_framework/results_parser
        run: |
          echo "Test dispatch payload \n Actions: ${{ github.event.action }} \n Device: ${{ github.event.client_payload.dev }}"
